language: go
go:
  - 1.12.x

before_install:
  - export GO111MODULE="on"
  - go mod tidy
  - go get -t -v ./...
  - env

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - env

after_success:
  - env
  - bash <(curl -s https://codecov.io/bash)
