language: go
go:
  - 1.19.x

before_install:
  - export GO111MODULE="on"
  - go mod tidy
  - go get -t -v ./...

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
