---
apiVersion: v1
kind: Template
metadata:
  name: entitlements-api-go
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: entitlements-api-go
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: service
      webServices:
        public:
          enabled: True
      minReplicas: ${{API_REPLICAS}}
      podSpec:
        initContainers:
          - name: bundle-sync
            image: quay.io/cloudservices/entitlements-api-go:${IMAGE_TAG}
            command: ["/bundle-sync"]
            env:
              - name: ENT_SUBS_HOST
                value: ${SUBS_HOST}
              - name: ENT_BUNDLE_INFO_YAML
                value: /bundles/bundles.yml
              - name: ENT_CERTS_FROM_ENV
                value: 'true'
              - name: ENT_RUN_BUNDLE_SYNC
                value: ${RUN_BUNDLE_SYNC}
            envFrom:
              - secretRef:
                  name: go-api-certs
            volumeMounts:
            - mountPath: /bundles
              name: default-entitlements-config
            inheritEnv: true    
        minReadySeconds: 15
        progressDeadlineSeconds: 600
        image: quay.io/cloudservices/entitlements-api-go:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
      envFrom:
        - secretRef:
            name: go-api-certs
      env:
        - name: ENT_PORT
          value: ${PORT}
        - name: ENT_ENTITLE_ALL
          value: ${ENTITLE_ALL}
        - name: ENT_CERTS_FROM_ENV
          value: 'true'
        - name: ENT_LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: ENT_AMS_HOST
          value: ${AMS_HOST}
        - name: ENT_BOP_URL
          value: ${BOP_URL}
        - name: ENT_BOP_ENV
          value: ${BOP_ENV}
        - name: ENT_CA_PATH
          value: /resources/ca.crt
        - name: ENT_SUBS_HOST
          value: ${SUBS_HOST}
        - name: ENT_COMPLIANCE_HOST
          value: ${COMPLIANCE_HOST}
        - name: ENT_OPENAPI_SPEC_PATH
          value: /apispec/api.spec.json
        - name: ENT_BUNDLE_INFO_YAML
          value: /bundles/bundles.yml
        - name: GLITCHTIP_DSN
          valueFrom:
            secretKeyRef:
              name: ${GLITCHTIP_SECRET}
              key: dsn
              optional: true
        - name: ENT_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oidc
              key: client_id
        - name: ENT_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc
              key: client_secret
        - name: ENT_BOP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: entitlements-api
              key: client_id
        - name: ENT_BOP_TOKEN
          valueFrom:
            secretKeyRef:
              name: entitlements-api
              key: token
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: '3000'
      prometheus.io/scrape: 'true'
    labels:
      app: entitlements-api-go
    name: entitlements-api-go
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 8000
    selector:
      app: entitlements-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

parameters:
- description: Log level for the application
  name: LOG_LEVEL
  required: false
  value: info
- description: Port for listener
  name: PORT
  value: '8000'
- description: Subscriptions Service API endpoint
  name: SUBS_HOST
  value: https://subscription.qa.api.redhat.com
- description: Account Management Service URL
  name: AMS_HOST
  value: https://api.openshift.com
- description: Back Office Proxy URL
  name: BOP_URL
  value: https://backoffice-proxy.apps.ext.spoke.prod.us-west-2.aws.paas.redhat.com/v1/users
- description: Back Office Proxy environment to query for users in
  name: BOP_ENV
  value: 'stage'
  required: true
- description: Export Compliance Service API endpoint
  name: COMPLIANCE_HOST
  value: https://export-compliance.dev.api.redhat.com
- description: Name of the entitlements-config config map
  name: CONFIG_MAP_NAME
  value: entitlements-config
- description: The number of replicas to use in the deployment
  name: REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Flag to determine whether or not to sync bundles on init
  name: RUN_BUNDLE_SYNC
  required: false
  value: 'false'
- description: Flag to determine whether or not to entitle all by default and mock calls to IT
  name: ENTITLE_ALL
  required: false
  value: 'false'
- description: The name of the Glitchtip secret
  name: GLITCHTIP_SECRET
  required: false
  value: 'entitlements-secret'